services:
  altivec-intelligence:
    image: ghcr.io/jeffreybergier/altivec-intelligence:latest
    stdin_open: true
    tty: true
    environment:
      - IS_SANDBOX=1
    volumes:
      - ~/.altivec:/root
      - .:/repo
    working_dir: /repo
    entrypoint: /bin/bash
    command: -lc "altivec-chooser"

  shell:
    image: ghcr.io/jeffreybergier/altivec-intelligence:latest
    environment:
      - STRAPPY_HOME=${STRAPPY_HOME:-/repo/backups}
      - GITHUB_TOKEN=${GITHUB_TOKEN:-}
    volumes:
      - ~/.strappy:/root
      - .:/repo
    working_dir: /repo/source

  strappy:
    image: ghcr.io/jeffreybergier/altivec-intelligence:latest
    stdin_open: true
    tty: true
    environment:
      - STRAPPY_HOME=${STRAPPY_HOME:-/repo/backups}
      - GITHUB_TOKEN=${GITHUB_TOKEN:-}
    volumes:
      - ~/.strappy:/root
      - .:/repo
    working_dir: /repo/source
    entrypoint: /bin/bash -lc 'npm install --no-fund --no-audit --loglevel=error >/dev/null && exec npm run --silent strappy -- "$@"' bash
